### ISSUE TITLE
integration in glpi ?

### ISSUE THREAD

**Issue by orthagh** [edgardmessias/autologin#1]
hello @edgardmessias (best wishes !)

I validated your plugin in the [catalogue](http://plugins.glpi-project.org/#/plugin/autologin)
But, this "enhancement" could be better in the core.

Could you think about sending a pull request ?

**Comment by edgardmessias** [comment]
hello @orthagh 

Yes, I'm going to create an pull request, I'll leave the plugin for older versions of GLPI

**Comment by edgardmessias** [comment]
@orthagh , now support to "Remember me function".

You can add this plugin in calalogue?

**Comment by orthagh** [comment]
Yeah sure.

I have an error on the import process but it will be fixed soon

**Comment by edgardmessias** [comment]
Thanks

**Comment by orthagh** [comment]
It's up: http://plugins.glpi-project.org/#/plugin/autologin

I have an issue with some plugins (with 404 xml) who break my bg task.
i temporary forced a manuel sync to have your plugin imported in the site.

**Comment by edgardmessias** [comment]
First, Thanks @orthagh 

What do you think of creating an XSD for the XML plugin?
With this you can even validate the XML

**Comment by orthagh** [comment]
in fact, we have a xml validation (on submit)

but, there is some hidden case where validations seems to pass and crash the process.
Anyway, i found the issue (incorrect exception handling): https://github.com/glpi-project/plugins/commit/507d0c520d0a7c62f91dede4831efb8c7d9ff3a5

**Comment by edgardmessias** [comment]
See glpi-project/glpi#1547
